"""Prompt templates, selected by `prompt_variant`.

Two fields describe the prompt and they do NOT overlap:

    context         WHAT the agent is given on a retry — nothing (`na`), the
                    verbatim prior attempts (`full`), or self-written summaries
                    of them (`summary`). An experimental axis about CONTENT.

    prompt_variant  HOW that is worded — which template. Every difference in
                    wording lives here, including whether the retry note names
                    the horizon ("This is attempt 3 of 10").

`full` / `full-nohorizon` / `full-noframe` used to be three `context` values.
They are not three contexts: all three hand the agent the same verbatim history.
They differ only in the sentence wrapped around it, which is a template concern.
So they are three VARIANTS of one context.

Adding a variant is one entry in VARIANTS below — no migration, no new column.
Editing an existing template's wording means MINTING A NEW VARIANT NAME, never
editing a spec in place: the name is what stops new attempts from resuming into
data generated by the old wording.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class PromptSpec:
    """What a variant does to the retry framing.

    horizon      emit "This is attempt <t> of <k>." — the only place `k` reaches
                 the actor, and therefore the only reason `k` is part of a run's
                 identity (see core.ids.k_affects_prompt).
    retry_frame  emit the "you will get feedback / review your previous
                 attempt(s)" sentence. Without it the actor still SEES prior
                 attempts; it is simply never told it is in a retry loop.
    """
    horizon: bool
    retry_frame: bool
    description: str


# The three framings. Named separately from the variant names so that `v1` and
# `legacy` can share one without duplicating its definition.
_FRAMINGS = {
    "default":   PromptSpec(horizon=True,  retry_frame=True,
                            description="horizon count + retry framing"),
    "nohorizon": PromptSpec(horizon=False, retry_frame=True,
                            description="retry framing, no count — isolates "
                                        "knowing-the-horizon from knowing-you-can-retry"),
    "noframe":   PromptSpec(horizon=False, retry_frame=False,
                            description="no note at all; history is still shown"),
}

# variant name -> framing. `legacy` marks runs made before variants were
# versioned: their templates were never given a name, so claiming `v1` would
# assert a provenance we cannot check.
VARIANTS = {
    "v1":                _FRAMINGS["default"],
    "v1-nohorizon":      _FRAMINGS["nohorizon"],
    "v1-noframe":        _FRAMINGS["noframe"],
    "legacy":            _FRAMINGS["default"],
    "legacy-nohorizon":  _FRAMINGS["nohorizon"],
    "legacy-noframe":    _FRAMINGS["noframe"],
}

DEFAULT_VARIANT = "v1"


def spec(prompt_variant):
    """The PromptSpec for a variant name. Unknown names fail loudly — a typo
    must not silently fall back to the default wording and quietly produce data
    that looks like a different experiment."""
    try:
        return VARIANTS[prompt_variant]
    except KeyError:
        raise ValueError(
            f"unknown prompt_variant {prompt_variant!r}; known: {sorted(VARIANTS)}. "
            f"Add it to core/prompts.py VARIANTS — and mint a NEW name rather than "
            f"editing an existing one, so runs cannot resume across a wording change."
        ) from None


def retry_note(spec_, *, t, k, has_history):
    """The sentence placed between the task and the prior-attempt blocks.

    Empty string when the variant emits no framing at all.
    """
    if not spec_.horizon and not spec_.retry_frame:
        return ""
    note = f"This is attempt {t + 1} of {k}." if spec_.horizon else ""
    if spec_.retry_frame:
        note += (" Review your previous attempt(s) and the feedback below, then "
                 "provide an improved answer." if has_history else
                 " If this attempt does not pass, you will receive feedback and can "
                 "revise it on the remaining attempts.")
    return note.strip()
